name: Test deploy

on:
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Productions
    permissions:
      contents: read
      deployments: write
    name: Deploy to Github Pages
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check env variables
        run: |
          if [ -z "${{ secrets.PUBLIC_CMS_KEY }}" ] || [ -z "${{ secrets.PIRIVATE_CMS_KEY }}" ] || [ -z "${{ secrets.PUBLIC_API_URL }}" ] || [ -z "${{ secrets.PUBLIC_IMG_URL }}" ]; then
          echo "Missing required environment variables."
          echo "${{ secrets.PIRIVATE_CMS_KEY }}"
          exit 1
          fi
        env:
          PUBLIC_CMS_KEY: ${{ secrets.PUBLIC_CMS_KEY }}
          PIRIVATE_CMS_KEY: ${{ secrets.PIRIVATE_CMS_KEY }}
          PUBLIC_API_URL: ${{ secrets.PUBLIC_API_URL }}
          PUBLIC_IMG_URL: ${{ secrets.PUBLIC_IMG_URL }}
